services:
  db:
    image: postgres:15-alpine
    container_name: nexusai_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - nexusai_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  nexusai_pgdata:
