export enum SsiMetrica {
  SSI_SETOR = 'SSI_SETOR',
  SSI_REDE = 'SSI_REDE',
  SSI_TOTAL = 'SSI_TOTAL',

  PILAR_MARCA = 'PILAR_MARCA',
  PILAR_PESSOAS_CERTAS = 'PILAR_PESSOAS_CERTAS',
  PILAR_INSIGHTS = 'PILAR_INSIGHTS',
  PILAR_RELACIONAMENTOS = 'PILAR_RELACIONAMENTOS',

  IMPRESSOES_PUBLICACAO = 'IMPRESSOES_PUBLICACAO',
  VISUALIZACOES_PERFIL = 'VISUALIZACOES_PERFIL',
  OCORRENCIAS_PESQUISA = 'OCORRENCIAS_PESQUISA',
  TAXA_RECRUTADORES = 'TAXA_RECRUTADORES',

  CANDIDATURAS_SIMPLIFICADAS = 'CANDIDATURAS_SIMPLIFICADAS',
  CANDIDATURAS_VISUALIZADAS = 'CANDIDATURAS_VISUALIZADAS',
  CURRICULOS_BAIXADOS = 'CURRICULOS_BAIXADOS',
  CONTATOS_RH = 'CONTATOS_RH',

  PUBLICACOES_SEMANA = 'PUBLICACOES_SEMANA',
  INTERACOES_COMENTARIOS = 'INTERACOES_COMENTARIOS',
  CONTRIBUICOES_ARTIGOS = 'CONTRIBUICOES_ARTIGOS',

  PEDIDOS_CONEXAO_HEADHUNTERS = 'PEDIDOS_CONEXAO_HEADHUNTERS',
  PEDIDOS_CONEXAO_DECISORES = 'PEDIDOS_CONEXAO_DECISORES',
  MENSAGENS_RECRUTADORES = 'MENSAGENS_RECRUTADORES',
  MENSAGENS_NETWORKING = 'MENSAGENS_NETWORKING',
  CAFES_AGENDADOS = 'CAFES_AGENDADOS',
  CAFES_TOMADOS = 'CAFES_TOMADOS',

  ENTREVISTAS_REALIZADAS = 'ENTREVISTAS_REALIZADAS',
  ENTREVISTAS_FASE_FINAL = 'ENTREVISTAS_FASE_FINAL',
  CARTAS_OFERTA = 'CARTAS_OFERTA',
}
